version: 2
jobs:
  build:
    working_directory: ~/booking-engine
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: booking-engine-{{ checksum "pom.xml" }}

      - run: mvn clean install -DskipTests
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: booking-engine-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/booking-engine-0.0.1-SNAPSHOT.jar

      - run: >
          mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=${SONAR_API_ORGANIZATION}
          -Dsonar.login=${SONAR_API_LOGIN}
