@startuml
:roomCreatedEvent;
repeat
:CreateSlotUseCase|
->slotCreatedEvent;
fork
  :FindNextSlotStateUseCase|
  if (pre reservation needs slot?) then (yes)
    ->slotRequiresPreReservationEvent;
    :PreReserveSlotUseCase|
    ->slotPreReservedEvent;
  elseif (class needs slot?) then (yes)
    ->slotRequiresPreReservationEvent;
    :PreReserveSlotUseCase|
    ->slotPreReservedEvent;
  elseif (auctionRequired?) then (yes)
    ->auctionRequiredEvent;
    :StartAuctionUseCase|
    ->auctionStartedEvent;
    :ScheduleFinishActionUseCase|
    -[dashed]->auctionFinishedEvent;
    (A)
    detach
    (A)
    -[dashed]->auctionFinishedEvent;
    :FinishAuctionUseCase|
    if (auctionWinnerFound?) then (yes)
      ->auctionWinnerFoundEvent;
      :PreReserveSlotUseCase|
      ->slotPreReservedEvent;
    else (no)
      ->auctionUnsuccessfulEvent;
      :MakeSlotAvailableUseCase|
      ->slotMadeAvailableEvent;
    endif
  else (no)
    ->slotCanBeMadeAvailableEvent;
    :MakeSlotAvailableUseCase|
  endif
  stop
fork again
  :ScheduleNextSlotUseCase|
  -[dashed]->slotRequiredEvent;
  (B)
  detach
  (B)
@enduml
